import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#fcf8ff",
        "surface-dim": "#dad7f3",
        "surface-bright": "#fcf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f2ff",
        "surface-container": "#efecff",
        "surface-container-high": "#e8e5ff",
        "surface-container-highest": "#e2e0fc",
        "on-surface": "#1a1a2e",
        "on-surface-variant": "#424750",
        "inverse-surface": "#2f2e43",
        "inverse-on-surface": "#f2efff",
        "outline": "#737781",
        "outline-variant": "#c2c6d1",
        "surface-tint": "#305f9b",
        "primary": "#00386b",
        "on-primary": "#ffffff",
        "primary-container": "#1b4f8a",
        "on-primary-container": "#9ac2ff",
        "inverse-primary": "#a6c8ff",
        "primary-fixed": "#d4e3ff",
        "primary-fixed-dim": "#a6c8ff",
        "on-primary-fixed": "#001c3a",
        "on-primary-fixed-variant": "#0e4782",
        "secondary": "#006a6a",
        "on-secondary": "#ffffff",
        "secondary-container": "#77f3f2",
        "on-secondary-container": "#006e6e",
        "secondary-fixed": "#7af5f5",
        "secondary-fixed-dim": "#5bd9d9",
        "on-secondary-fixed": "#002020",
        "on-secondary-fixed-variant": "#004f50",
        "tertiary": "#34383b",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#4b4f52",
        "on-tertiary-container": "#bdc1c4",
        "tertiary-fixed": "#e0e3e7",
        "tertiary-fixed-dim": "#c3c7cb",
        "on-tertiary-fixed": "#181c1f",
        "on-tertiary-fixed-variant": "#43474b",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "background": "#fcf8ff",
        "on-background": "#1a1a2e",
        "surface-variant": "#e2e0fc",
        "whatsapp": "#25D366",
      },
      fontFamily: {
        "display-lg": ['"Playfair Display"', "serif"],
        "display-lg-mobile": ['"Playfair Display"', "serif"],
        "headline-md": ['"Playfair Display"', "serif"],
        "headline-sm": ['"Playfair Display"', "serif"],
        "body-lg": ['"IBM Plex Sans"', "sans-serif"],
        "body-md": ['"IBM Plex Sans"', "sans-serif"],
        "body-sm": ['"IBM Plex Sans"', "sans-serif"],
        "button": ['"IBM Plex Sans"', "sans-serif"],
        "label-technical": ['"Space Mono"', "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "button": ["16px", { lineHeight: "1", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-technical": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }],
      },
      spacing: {
        "xs": "4px",
        "sm": "12px",
        "md": "24px",
        "lg": "48px",
        "xl": "80px",
        "base": "8px",
        "gutter": "24px",
        "container-max": "1280px",
      },
      borderRadius: {
        "sm": "0.25rem",
        "DEFAULT": "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "2xl": "2rem",
        "full": "9999px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      keyframes: {
        "subtle-pulse": {
          "0%, 100%": { opacity: "0.6", transform: "scale(1)" },
          "50%": { opacity: "1", transform: "scale(1.05)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
        "fade-in-up": {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "pulse-slow": "subtle-pulse 4s ease-in-out infinite",
        float: "float 6s ease-in-out infinite",
        "float-delayed": "float 6s ease-in-out 3s infinite",
        "fade-in-up": "fade-in-up 0.6s ease-out forwards",
      },
      boxShadow: {
        soft: "0 4px 20px rgba(27, 79, 138, 0.08)",
        card: "0 4px 20px rgba(27, 79, 138, 0.05)",
        "teal-glow": "0 0 15px rgba(58, 191, 191, 0.2)",
      },
    },
  },
  plugins: [],
};

export default config;
